### ISSUE TITLE
Overriding resource type

### ISSUE THREAD

**Issue by knownasilya** [brainwipe/NJsonApiCore#26]
The usecase is if I pass back a view model, which might have the name `UserViewModel`, the json api type ends up being `userViewModel`, but I want it to be `user`. Is there a way to make this work?

**Comment by brainwipe** [comment]
Not with the code as it is. You can always fork and edit but it's not supported currently. One of the assumptions that was made very early on is to simplify by making the name of the resource match the name of the class. You can always separate your View Models by namespace rather than by type name.
