### ISSUE TITLE
Serializing Complex Data Types Specifically Dictionary<string, object>

### ISSUE THREAD

**Issue by Darth-Arminius** [brainwipe/NJsonApiCore#28]
We are trying to serialize this class which contains a Dictionary<string, object> but when we attempt to do so we get this error:

An exception of type 'System.InvalidOperationException' occurred in NJsonApiCore.dll but was not handled in user code

Additional information: Type MyResource was registered to have a linked resource dictionaryData of type KeyValuePair2 which was not registered. Register resource type KeyValuePair2 or disable serialization of that property.

Right after this line:

configBuilder.
                Resource<MyResource, MyController>().
                WithAllProperties();

The resource class looks something like this:

public class MyResource
    {
        public int Id { get; set; }
        public Dictionary<string, object> DictionaryData{ get; set; }
        public string Name { get; set; }
    }

**Comment by brainwipe** [comment]
NJsonApiCore thinks that `DictionaryData` is a resource because it's not a simple type. That's a limitation of the library. It's not an easy fix, so if you're stuck I'd recommend mapping your dictionary contents into simple types.

**Comment by Darth-Arminius** [comment]
Ah that's a shame. Well thank you anyway for letting me know.

**Comment by burgessl** [comment]
Did you want to serialize DictionaryData as an attribute (rather than a relationship)? It is possible to do this but by default the 'WithAllProperties' method will (as brainwipe mentioned) determine that DictionaryData is a relationship as it isn't a simple type.

You have two options:
- Don't use WithAllProperties and manually add each property you want on the resource and use 'WithSimpleProperty' for those properties you want to be attributes
- Replace the default IPropertyScanningConvention  with one that does what you want (we have an attribute we stick on things we want to be attributes and a convention that uses this to determine whether a property is a relationship or an attribute

Hope that helps

**Comment by brainwipe** [comment]
Thanks to @burgessl, this is the correct method. `WithAllProperties` assumes that every property on the resource is a simple type.
