### ISSUE TITLE
Ability to disable link building

### ISSUE THREAD

**Issue by Sprot** [brainwipe/NJsonApiCore#29]
Is there a possibility to disable link building?

I have some specific action models that are not related to any specific id. But as Id field is a must in jsonapi I generate new Guid for ID. But I would like to disable link building for such objects as those links are wrong and do not represent this object correctly.

**Comment by brainwipe** [comment]
Link building is part of the json api and to remain compliant, you need to have links for all related resources. 

Perhaps there might be a different way to model your problem. Can you give an example of the JSON you want to send and some C# for your models?

**Comment by Sprot** [comment]
I query a count of objects over a period and return that count with reflected filters back.

	public class ActionObject
	{
	  public ActionObject()
	  {
		public ActiveClientCardsCount()
		{
			Id = Guid.NewGuid().GetHashCode();
		}
		
		public int Id { get; set; }

		public int NumberOfObjects { get; set; }
		
		public IEnumerable<short> UserIds { get; set; }
	  }
	}

My api call is /Controller/Action?UserIds=1,2,3,4

Now the ActionObjec is not a resource itself - it is generated over number of different tables in DB so now when the link now is generated it is pointing to the resource that is not available

"data": [
    {
      "id": "-1898486253",
      "type": "activeObjectCounts",
      "attributes": {
        "userIds": [1,2,3,4],
		"period": 1,
        "numberOfObjects": 3284
      },
      "links": {
        "self": "http://localhost:50873/Controller/-1898486253"
      }
    }
	{
      "id": "-189987363",
      "type": "activeObjectCounts",
      "attributes": {
        "userIds": [1,2,3,4],
		"period": 2,
        "numberOfObjects": 2
      },
      "links": {
        "self": "http://localhost:50873/Controller/-189987363"
      }
    }
  ],
  "links": {
    "self": "http://localhost:50873/Controller/Action?UserIds=1,2,3,4&Periods=1,2"
  },
  "jsonapi": {
    "version": "1.0"
  }

**Comment by brainwipe** [comment]
I am beginning to understand, thank you!

Now there is a core idea to API design (not just json:api) that a _resource_ does not have to be the same thing as a _domain entity_. A resource is often a combination of domain entities or something that doesn't even exist. Choosing resources properly is important and in json:api there are only resources. A resource must be uniquely identifiable as per REST/http.

It appears that you want to ask the API "tell me the number of active objects for these users for this period". I'm also going to assume that User is a Resource too. Am I right? I'll assume so and keep going...

It seems to me that your resource is actually **Period** and that you're returning multiple periods. So I would reorganise the API to be the following:

First, let's get all the periods with all the users:
```
GET http://localhost:50873/Controller/Periods
{
    "data": [
        {
            "id": "1",
            "type": "periods",
            "attributes": {
                "numberOfObjects": 3284123213
            },
            "links": {
                "self": "http://localhost:50873/Controller/Periods/1"
            },
        },
        {
            "id": "2",
            "type": "periods",
            "attributes": {
                "numberOfObjects": 2123213
            },
            "links": {
                "self": "http://localhost:50873/Controller/Periods/2"
            }
        },
       /** More periods go in here **/
    ],
    "links": {
        "self": "http://localhost:50873/Controller/Periods"
    },
    "jsonapi": {
        "version": "1.0"
    }
}
```

Now your example doesn't want all periods and all users, so we must use the `filter` attribute (that you implement yourself). I'm going to use the [json:api filtering](http://jsonapi.org/recommendations/#filtering) as an example:

```
GET http://localhost:50873/Controller/Periods?filter[periods]=1,2&filter[users]=1,2,3,4
{
    "data": [
        {
            "id": "1",
            "type": "periods",
            "attributes": {
                "numberOfObjects": 3284
            },
            "links": {
                "self": "http://localhost:50873/Controller/Periods/1"
            },
        },
        {
            "id": "2",
            "type": "periods",
            "attributes": {
                "numberOfObjects": 2
            },
            "links": {
                "self": "http://localhost:50873/Controller/Periods/2"
            }
        }
    ],
    "links": {
        "self": "http://localhost:50873/Controller/Periods?filter[periods]=1,2&filter[users]=1,2,3,4"
    },
    "jsonapi": {
    "version": "1.0"
   }
}
```

Note - the characters `[]` aren't allowed, they'll actually need to be URL encoded.

Now if you want to make this truly discoverable, I'd include Relationships to the Users within each Period. That will make your API payload a bit fatter and is only needed if you want the client to be able to move around your API.

**Comment by brainwipe** [comment]
I'd just like to add that json:api doesn't suit all domains! If the relationships/resources architecture of hypermedia seems like too much overhead and you don't need the discovery aspect then you might be better off building your own custom JSON.

**Comment by Sprot** [comment]
In reality my periods are not defined. They are dateTime filter elements. that relates to one field in database table.
Period {
DateTime StartDate;
DateTime EndDate
}

The link disable wouldn't make it not compatible with JSON:API as it is stated there:

> A document MAY contain any of these top-level members:
>
>   jsonapi: an object describing the server’s implementation
>    links: a links object related to the primary data.
>    included: an array of resource objects that are related to the primary data and/or each other (“included resources”).

I have ran link-less objects through schema validator and they pass.

**Comment by brainwipe** [comment]
Point taken about the links, it's a feature request for sure.

I think I am missing some things about your domain. 

How does client create the resource endpoint `/Controller/Action?UserIds=1,2,3,4`? Which resource contains this URI as a relationship?

**Comment by Sprot** [comment]
This is not a resource in itself. The method Action is in my system more like statistical method that goes over all the resource that is pointed by the Controller. 

For example we have a users and we want to have a distinct count of active users  who reported something in periods.
it is related to users but the point behind is more statistical not resource.

**Comment by brainwipe** [comment]
Ah, I think we're talking cross purposes. In json:api (and REST and HTTP) _everything_ is a resource. The page your're looking at is a resource. A jpeg is a resource. A resource is something that lives on an endpoint. Some resources are GET only, some are POST, some are PATCH. A resource is not the same thing as an entity in your system. A resource is simply a data structure that is returned, be it a statistic, a jpeg, a zip or good old fashioned formatted data from the database. When I say resource, it doesn't have to map to a row in a RDMS table or a document in a doc db. It can just be stats created out of thin air. As long as a client can go back to the URL and call it again and expect the same format, it's a resource.

If that definition really doesn't fit what you're trying to achieve then I'd avoid REST altogether because you're not getting the benefits of it. You can have a very good API that isn't rest; most OAuth systems are not REST and they're certainly not Hypermedia. They work just as well!

For Hypermedia (which json:api is one standard, HAL is another), the client does not build the URLs, they are all passed from the server. Amongst the benefits of this is that your API is discoverable: you don't have to write lots of API documentation, just enough to describe what the business objects are. You then give them the starting endpoint and they can discover your whole API from the links. If you don't get a link, you don't have access (NJsonApiCore doesn't do that yet but it's core to Hypermedia and will go in because I need it at work!).

For your Hypermedia API, your top level might look like:

```
GET http://localhost:50873/controller

"links": {
    "self": "http://localhost:50873/controller",
    "reports": "http://localhost:50873/controller/reports",
  },
```

Like all reports, statistics are resources. For example, your API might look like:

`GET http://localhost:50873/controller/reports`

Would not have data of its own but instead relationships to all the reports that the user can see. If the client doesn't have access to any reports, then this resource is a 403. So the top level `links` object might look like:

```
"links": {
    "self": "http://localhost:50873/controller/reports",
    "distinct_user_periods": "http://localhost:50873/controller/distinct_user_periods"
    "distinct_user_periods_first": "http://localhost:50873/controller/distinct_user_periods?page[offset]=1"
    "distinct_user_periods_last": "http://localhost:50873/controller/distinct_user_periods?page[offset]=10"
  },
```

The report can be a single document, it just lives on the endpoint with `id` of 1 and the data is all inside the `attributes` like so:

```
GET http://localhost:50873/Controller/distinct_user_periods?filter[periods]=1,2&filter[users]=1,2,3,4
{
    "data": [
        {
            "id": "1",
            "type": "distinct_user_periods",
            "attributes": {
                "periods":[
                      {
                            "period": 1,
                            "numberOfObjects": 3284
                      },
                      {
                            "period": 2,
                            "numberOfObjects": 2
                      }
                ]
            },
            "links": {
                "self": "http://localhost:50873/Controller/distinct_user_periods?filter[periods]=1,2&filter[users]=1,2,3,4"
            }
        }
    ],
    "links": {
        "self": "http://localhost:50873/Controller/distinct_user_periods?filter[periods]=1,2&filter[users]=1,2,3,4"
    },
    "jsonapi": {
    "version": "1.0"
   }
}
```

You have to be careful with the Configuration of your resources if you're using this method as NJsonApiCore by default scans all the properties and will assume that every complex type is a resource.

I hope that helps!

**Comment by Sprot** [comment]
Thank you for taking time to explain this. This has been really informative and it helped a lot.

**Comment by Sprot** [comment]
How would you define the Report type using NJson. I tried different styles but failed to get the relation correct.

I defined new Controller for reports  - to act as a sub-controller. But I am failing to link different reports from the object.

If I defined Report like
public class Report
{
	public Report(){ Id=1;}
	public int Id {get; set;
}


And each report as a different class

public class ReportType
{
public ReportType()
{
  Id = "ReportType"
}
string Id {get; set;}
}

This way I got /report/ReportType links under the ReportType object but Report itself don't produce any links currently as I fail to link them properly.

When I made Report.ID as a string and operated report types as Id-s then I was not able to add filter parameters as NJson throwed exception.

**Comment by brainwipe** [comment]
You raise a fair point! I've had a play with the API and I have found a way to do what you want. It isn't the perfect way, which is why I've created #31.

Check out the MVCCore project in the examples/reports branch. 
You'll find a [Reports Controller](NJsonApiCore/src/NJsonApiCore.Web.MVCCore.HelloWorld/Controllers/ReportsController.cs) that has a [Report](NJsonApiCore/src/NJsonApiCore.Web.MVCCore.HelloWorld/Models/Report.cs) Model in which there is a dummy Statistics model.

```
GET http://localhost:60101/reports/1
{
  "data": {
    "id": "1",
    "type": "reports",
    "attributes": {},
    "relationships": {
      "statisticsReport": {
        "links": {
          "self": "http://localhost:60101/reports/1/relationships/statisticsReport",
          "related": "http://localhost:60101/reports/1/statisticsReport"
        },
        "data": {
          "id": "1",
          "type": "statisticsReports"
        }
      }
    },
    "links": {
      "self": "http://localhost:60101/reports/1"
    }
  },
  "links": {
    "self": "http://localhost:60101/reports/1"
  },
  "jsonapi": {
    "version": "1.0"
  }
}
```

You can then enumerate the relationships and get the related link to do:

```
GET http://localhost:60101/reports/1/statisticsReport
{
  "data": {
    "id": "1",
    "type": "statisticsReports",
    "attributes": {},
    "links": {
      "self": "http://localhost:60101/statisticsreport/1"
    }
  },
  "links": {
    "self": "http://localhost:60101/reports/1/statisticsReport"
  },
  "jsonapi": {
    "version": "1.0"
  }
}
```

Note that the self link of the second Statistics report is its own controller, so you need to add controllers for each child report in your configuration. Check out the [updated configuration](https://github.com/brainwipe/NJsonApiCore/blob/examples/reports/src/NJsonApiCore.Web.MVCCore.HelloWorld/NJsonApiConfiguration.cs). If you wanted a back link to the parent Reports then you could add a property on the `StatisticsReport` class and NJsonApiCore will create the links.

I hope that helps!
