### ISSUE TITLE
LinkedResource IEnumerable

### ISSUE THREAD

**Issue by Sprot** [brainwipe/NJsonApiCore#30]
If` LinkedResource` type is `IEnumerable` then `ResourceConfigurationBuilder.WithLinkedResource` fails to get `linkedType`. If I set it to `IList` then it works.

Error pattern:
```
public class Post{
  public in Id {get; set;}
}

public class Author{
  public int Id {get; set;}
  public IEnumerable<Post> Posts {get; set;}
}

configBuilder
  .Resource<Author, AuthorController>()
  .WithIdSelector(p => p.Id)
  .WithLinkedResource (p => p.Posts);
```

**Comment by brainwipe** [comment]
This is working as designed.

Using `IEnumerable` is like saying: 

> I don't really care when you work out what's in the list, just do it eventually.

Now that's cool if you're building a query that's gone to run on a database or you have a big collection in memory that you're working on. However, if data is going outside of a _context boundary_ (I'll come back to that, stay with me!) then you should say "The Data is X".

In this case, you're saying that the Author API model has "a bunch of posts, I don't care what they are until later" but the API model _must_ care right now because it's the last time the data is touched by the API. After that, it's out in the world. That's the context boundary. `IEnumerable` delays the execution of the building of list of entities but that doesn't make sense for an API because client can't add `Where` clauses onto it. That's why we enforce `IList`, we are telling the programmer (you in this case) that `IEnumerable` doesn't cut it and they need to be dealing with lists, be they arrays or linked lists.

**That said, there should be a better error message to explain how to fix it.**
