### ISSUE TITLE
non-JSONAPI controllers don't work with requests without Content-Type

### ISSUE THREAD

**Issue by cnolewajka** [brainwipe/NJsonApiCore#33]
If one mixes JSONAPI and non-JSONAPI controllers in the project, and would like the non-JSONAPI controllsers to respond to GET requests with emtpy/missing Content-Type header, the ActionFilter uses this criteria to decide if the call is allowed or not:

        private bool ValidateContentTypeHeader(MediaTypeHeaderValue contentType)
        {
            return contentType == null || contentType.MediaType == configuration.DefaultJsonApiMediaType;
        }

and throws.

According to JSONAPI spec, the calls always should have the Content-Type present with the value applicaiton/vnd.app+json.

It looks like the null check is not required and should be removed.

**Comment by brainwipe** [comment]
The problem is a little bit bigger (and annoying) than this. NJsonApiCore does not support a mixed project of non-NJsonApiCore controllers and standard MVC/WebAPI.

The problem is that the action filters are attached to every request but it applies itself to every API call rather than controllers that are registered to NJsonApiCore. It needs to be changed so that if a request comes into a controller then it checks to see if the Controller is registered and do nothing/ignore it if so.

The code should never get to the line above, it should have decided not to continue because the controller has no resource map.

**Comment by AdamLJohnson** [comment]
I have run across this as well. My hack until something better can be created is that I implemented a custom filter that inherits JsonApiActionFilter. This simply looks for requests that have a `application/json` content type. 
`if (context.HttpContext.Request.ContentType == "application/json") return;`

Since JsonAPI requests should be `applicaiton/vnd.app+json` this effectively skips over the NJsonApiCore bits. You could also look for an empty content-type.

**Comment by brainwipe** [comment]
I think there might be a neat solution hidden in there. Perhaps what the filter should do is check to see if the Controller is registered and if it is _then_ it should check for the content type.

The behaviour would then be that if you try and call a NJsonApiCore registered Controller then you must have the content type, if you're calling some other controller then you don't.

I'll sleep on it but that would solve the problems you're both having and still be a neat solution.

Thanks!

**Comment by AdamLJohnson** [comment]
I am also (probably an anti-pattern) putting actions in my NJsonApiCore registered Controller that are not JsonAPI. This allows me to keep my data access (CRUD) actions and my server side (like task assignments) actions close to each other. 

Another way I have toyed with that is not based on the content-type is to use an attribute (mine is called `SkipJsonApi`) to decorate the action or controller. When the filter sees that the requests `context.ActionDescriptor` has the attribute it just does a `return;` to skip the rest of the NJsonApiCore.

It's another hack that I have not had a lot of time to go back and double check, but it worked well the few times i have used it.

```
private static bool ShouldSkipAction(ActionDescriptor context)
{
    var methodInfo = ((Microsoft.AspNetCore.Mvc.Controllers.ControllerActionDescriptor) context).MethodInfo;
    var customAttributes = methodInfo.CustomAttributes;
    bool skipAction = customAttributes.Any(a => a.AttributeType == typeof(SkipJsonApiAttribute));
    return skipAction;
}
```

**Comment by brainwipe** [comment]
I don't think it's an anti Pattern to json:api output and normal API output. As the Programmer, you shouldn't work around json:api to build the API that makes sense to you and your application.

For ease of use, json:api assumes that the whole API is json:api. That's a little arrogant of the NJsonApiCore library! 

As long as your team understands why the work arounds are there, they're not hacks! You're working within the limitations of NJsonApiCore - which are considerable! No doubt we will end up implementing something similar to your Skip attribute.

**Comment by cnolewajka** [comment]
I support the solution when a check is done in the filter if the controller is registered with NJSONAPICORE. If it's not, then rest should be skipped. I personally created a decorator filter class that does the check. I guess such a check in the original filter would be sufficient. 

For the other non-jsonapi methods on a controller, that I would consider an extra. I don't see why a developer should attribute all non-njsonapicore controllers' action methods with an attribute to have them work. So, this approach should only be considered for njsonapicore registered controllers, where we want to have non-jsonapi actions. But then, wouldn't you want to separate those into another controller not registered with njsonapicore controller for clarity? So, I would consider actually not implementing the attribute approach at all.

**Comment by brainwipe** [comment]
Just a note - this already worked on the MVCCore library. So the fix is only required for MVC5.
